Modified Files:
LoadImages: corrected typo 

split: bug fix

modelFit: 1.  Major update to allow observation frequencies as input. 
                2. Also change default behavior for multiple assignment  to mixture model.

mnlfit: 1. Major update to allow observation frequencies as input. 
          2. Returns the total number of observations as an output argument

buildpolyreg: Expanded help 

fact2reg: Expanded help

makeregressor: Expanded help

BinManager: Fix minor bug 

readEDF: 1. Fix code error in specification of eye.
              2. Specify eye of saccade.
              3. Fix error in computing index into xdat for fixations.

RegManager: Fix error in the normalization by mean bin area. 


Added Files:

setModelData:  simpler interface for setting modelData structure

logperror:   compute log probability and error, and log probability ratios and error using error propagation.

collapseX:  collapse over the columns of matrix X, returning uniqe rows and counts for each.
 
cov2corr:   one-liner for converting covariance matrix to correlation matrix.